variable "project_id" { type = string }
variable "region" { type = string }
variable "bucket_name" { description = "Bucket to trigger on" }
variable "source_bucket_name" { description = "Bucket to store source code" }
variable "db_host" { type = string }
variable "db_name" { type = string }
variable "db_user" { type = string }
variable "db_password_secret_id" { description = "Resource ID of the DB password secret" }
variable "vpc_name" { description = "VPC Name for Connector" }
